DROP TRIGGER DEV."FORNECEDORES_SEQ_TRIGGER";
DROP TRIGGER DEV."PEDIDOS_SEQ_TRIGGER";
DROP TRIGGER DEV."PRODUTOS_SEQ_TRIGGER";
DROP TRIGGER DEV."QUALIDADES_SEQ_TRIGGER";
DROP TRIGGER DEV."STATUS_SEQ_TRIGGER";