CREATE OR REPLACE VIEW DW_USER.ALL_PEDIDOS_VIEW AS 
SELECT 
    p.PDD_ID,
    p.PDD_DATA,
    p.PDD_STT_ID,
    p.PDD_FOC_ID,
    p.PDD_VALOR_TOTAL,
    p.PDD_VALOR_PAGO,
    p.PDD_QAL_ID
FROM DEV.PEDIDOS p

UNION ALL

SELECT 
    hp.HPDD_ID,
    hp.HPDD_DATA,
    hp.HPDD_STT_ID,
    hp.HPDD_FOC_ID,
    hp.HPDD_VALOR_TOTAL,
    hp.HPDD_VALOR_PAGO,
    hp.HPDD_QAL_ID
FROM DEV.HPEDIDOS hp