CREATE TABLE DEV.QUALIDADES (
    qal_id NUMBER(6,0) NOT NULL,
    qal_nome VARCHAR(255) CONSTRAINT CK_QAL_NN_01 NOT NULL
);
/
ALTER TABLE DEV.QUALIDADES ADD CONSTRAINT PK_QAL PRIMARY KEY (qal_id);
/
CREATE TABLE DEV.FORNECEDORES (
    foc_id NUMBER(6,0) NOT NULL,
    foc_nome VARCHAR(255) CONSTRAINT CK_FOC_NN_01 NOT NULL,
    foc_difereca NUMBER(5,2) DEFAULT 0 CONSTRAINT CK_FOC_NN_02 NOT NULL
);
/
ALTER TABLE DEV.FORNECEDORES ADD CONSTRAINT PK_FOC PRIMARY KEY (foc_id);
/
CREATE TABLE DEV.STATUS (
    stt_id NUMBER(6,0) NOT NULL,
    stt_nome VARCHAR(255) CONSTRAINT CK_STT_NN_01 NOT NULL
);
/
ALTER TABLE DEV.STATUS ADD CONSTRAINT PK_STT PRIMARY KEY (stt_id);
/
CREATE TABLE DEV.PRODUTOS (
    pdt_id NUMBER(6,0) NOT NULL,
    pdt_nome VARCHAR(255) CONSTRAINT CK_PDT_NN_01 NOT NULL,
    pdt_preco NUMBER(4,2) CONSTRAINT CK_PDT_NN_02 NOT NULL
);
/
ALTER TABLE DEV.PRODUTOS ADD CONSTRAINT PK_PDT PRIMARY KEY (pdt_id);
/
CREATE TABLE DEV.PEDIDOS (
    pdd_id NUMBER(6,0) NOT NULL,
    pdd_data DATE CONSTRAINT CK_PDD_NN_01 NOT NULL,
    pdd_stt_id NUMBER(6,0) CONSTRAINT CK_PDD_NN_02 NOT NULL,
    pdd_foc_id NUMBER(6,0) CONSTRAINT CK_PDD_NN_03 NOT NULL,
    pdd_valor_total NUMBER(5,2) CONSTRAINT CK_PDD_NN_04 NOT NULL,
    pdd_valor_pago NUMBER(5,2) CONSTRAINT CK_PDD_NN_05 NOT NULL,
    pdd_qal_id NUMBER(6,0)
);
/
ALTER TABLE DEV.PEDIDOS ADD CONSTRAINT PK_PDD PRIMARY KEY (pdd_id);
ALTER TABLE DEV.PEDIDOS ADD CONSTRAINT FK_PDD_STT FOREIGN KEY (pdd_stt_id) REFERENCES DEV.STATUS(stt_id);
ALTER TABLE DEV.PEDIDOS ADD CONSTRAINT FK_PDD_FOC FOREIGN KEY (pdd_foc_id) REFERENCES DEV.FORNECEDORES(foc_id);
ALTER TABLE DEV.PEDIDOS ADD CONSTRAINT FK_PDD_QAL FOREIGN KEY (pdd_qal_id) REFERENCES DEV.QUALIDADES(qal_id);
/
CREATE TABLE DEV.PEDIDOS_PRODUTOS (
    ppd_pdd_id NUMBER(6,0) NOT NULL,
    ppd_pdt_id NUMBER(6,0) NOT NULL,
    ppd_quantidade NUMBER(6,0) CONSTRAINT CK_PPD_NN_01 NOT NULL
);
/
ALTER TABLE DEV.PEDIDOS_PRODUTOS ADD CONSTRAINT PK_PPD PRIMARY KEY (ppd_pdd_id, ppd_pdt_id);
ALTER TABLE DEV.PEDIDOS_PRODUTOS ADD CONSTRAINT FK_PPD_PDD FOREIGN KEY (ppd_pdd_id) REFERENCES DEV.PEDIDOS(pdd_id);
ALTER TABLE DEV.PEDIDOS_PRODUTOS ADD CONSTRAINT FK_PPD_PDT FOREIGN KEY (ppd_pdt_id) REFERENCES DEV.PRODUTOS(pdt_id);
/