CREATE SEQUENCE DEV."FORNECEDORES_SEQ" MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DEV."PEDIDOS_SEQ" MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DEV."PRODUTOS_SEQ" MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DEV."QUALIDADES_SEQ" MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DEV."STATUS_SEQ" MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;