CREATE OR REPLACE TRIGGER DEV."FORNECEDORES_SEQ_TRIGGER" BEFORE INSERT ON DEV.FORNECEDORES
FOR EACH ROW
BEGIN
    :NEW.foc_id := DEV.FORNECEDORES_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER DEV."PEDIDOS_SEQ_TRIGGER" BEFORE INSERT ON DEV.PEDIDOS
FOR EACH ROW
BEGIN
    :NEW.pdd_id := DEV.PEDIDOS_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER DEV."PRODUTOS_SEQ_TRIGGER" BEFORE INSERT ON DEV.PRODUTOS
FOR EACH ROW
BEGIN
    :NEW.pdt_id := DEV.PRODUTOS_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER DEV."QUALIDADES_SEQ_TRIGGER" BEFORE INSERT ON DEV.QUALIDADES
FOR EACH ROW
BEGIN
    :NEW.qal_id := DEV.QUALIDADES_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER DEV."STATUS_SEQ_TRIGGER" BEFORE INSERT ON DEV.STATUS
FOR EACH ROW
BEGIN
    :NEW.stt_id := DEV.STATUS_SEQ.NEXTVAL;
END;
/