-- Porcentagem de Pedidos Pago a Mais, Menos e Exatos
SELECT
    COALESCE(ROUND(SUM(CASE WHEN p.PDD_VALOR_TOTAL - p.PDD_VALOR_PAGO > 0 THEN 1 END)*100 / COUNT(p.PDD_ID), 2), 0) AS "Pago a menos", 
    COALESCE(ROUND(SUM(CASE WHEN p.PDD_VALOR_TOTAL - p.PDD_VALOR_PAGO = 0 THEN 1 END)*100 / COUNT(p.PDD_ID), 2), 0) AS "Exato",
    COALESCE(ROUND(SUM(CASE WHEN p.PDD_VALOR_TOTAL - p.PDD_VALOR_PAGO < 0 THEN 1 END)*100 / COUNT(p.PDD_ID), 2), 0) AS "Pago a mais"
FROM PEDIDOS p;