SELECT
    QAL_NOME,
    SUM(PPD_QUANTIDADE) AS TOTAL_VENDIDO,
    SUM(VALOR_ITEM) AS FATURAMENTO
FROM DW_USER.MV_QUALIDADE_STAGE
GROUP BY QAL_NOME
ORDER BY FATURAMENTO DESC;

/

SELECT
    QAL_NOME,
    SUM(PPD_QUANTIDADE) AS TOTAL_PRODUTOS_VENDIDOS
FROM DW_USER.MV_QUALIDADE_STAGE
GROUP BY QAL_NOME
ORDER BY TOTAL_PRODUTOS_VENDIDOS DESC;

/

SELECT
    QAL_NOME,
    ROUND(AVG(VALOR_ITEM), 2) AS TICKET_MEDIO
FROM DW_USER.MV_QUALIDADE_STAGE
GROUP BY QAL_NOME
ORDER BY TICKET_MEDIO DESC;

/

SELECT
    ESTACAO,
    QAL_NOME,
    TOTAL_VENDIDO
FROM (
    SELECT
        ESTACAO,
        QAL_NOME,
        SUM(PPD_QUANTIDADE) AS TOTAL_VENDIDO,
        RANK() OVER (
            PARTITION BY ESTACAO
            ORDER BY SUM(PPD_QUANTIDADE) DESC
        ) AS POSICAO
    FROM DW_USER.MV_QUALIDADE_STAGE
    GROUP BY
        ESTACAO,
        QAL_NOME
)
WHERE POSICAO = 1;