CREATE MATERIALIZED VIEW DW_USER.MV_QUALIDADE_STAGE
BUILD IMMEDIATE 
REFRESH FORCE
ON DEMAND
AS

SELECT
    QAL_NOME AS "QUALIDADE",
    -- PDT_NOME AS "NOME DO PRODUTO",
    ROUND(AVG(PDT_PRECO),2) AS "PREÇO PRODUTO",
    SUM(PPD_QUANTIDADE) AS "QUANT. PRODUTO",
    SUM(PDD_VALOR_TOTAL) AS "VALOR TOTAL",
    SUM(PDD_VALOR_PAGO) AS "VALOR PAGO",
    -- FOC_NOME AS "FORNECEDOR",
    SUM(PPD_QUANTIDADE * PDT_PRECO) AS "VALOR ITEM",
    SUM(PDD_VALOR_TOTAL - PDD_VALOR_PAGO) AS "VALOR A SER PAGO",
    EXTRACT(MONTH FROM PDD_DATA) || '/' || EXTRACT(YEAR FROM PDD_DATA) AS MES_ANO,
    CASE
        WHEN EXTRACT(MONTH FROM PDD_DATA) IN (12,1,2)
            THEN 'VERAO'
        WHEN EXTRACT(MONTH FROM PDD_DATA) IN (3,4,5)
            THEN 'OUTONO'
        WHEN EXTRACT(MONTH FROM PDD_DATA) IN (6,7,8)
            THEN 'INVERNO'
        ELSE 'PRIMAVERA'
    END AS ESTACAO
FROM DW_USER.ALL_QUALIDADES
GROUP BY QAL_NOME,
    -- PDT_NOME,
    EXTRACT(MONTH FROM PDD_DATA), EXTRACT(YEAR FROM PDD_DATA);
    -- FOC_NOME;
BEGIN
   dbms_mview.refresh('MV_QUALIDADE_STAGE', method => 'C', atomic_refresh => FALSE);
END;
