CREATE MATERIALIZED VIEW DW_USER.MV_QUALIDADE_STAGE
BUILD IMMEDIATE 
REFRESH FORCE
ON DEMAND
AS

SELECT
    PDT_ID,
    PDT_NOME,
    PDT_PRECO,
    PPD_PDD_ID,
    PPD_PDT_ID,
    PPD_QUANTIDADE,
    PDD_ID,
    PDD_DATA,
    PDD_STT_ID,
    PDD_FOC_ID,
    PDD_QAL_ID,
    QAL_NOME,
    PDD_VALOR_TOTAL,
    PDD_VALOR_PAGO,
    (PPD_QUANTIDADE * PDT_PRECO) AS VALOR_ITEM,
    (PDD_VALOR_TOTAL - PDD_VALOR_PAGO) AS VALOR_PENDENTE,
    EXTRACT(YEAR FROM PDD_DATA) AS ANO,
    EXTRACT(MONTH FROM PDD_DATA) AS MES,
    CASE
        WHEN EXTRACT(MONTH FROM PDD_DATA) IN (12,1,2)
            THEN 'VERAO'
        WHEN EXTRACT(MONTH FROM PDD_DATA) IN (3,4,5)
            THEN 'OUTONO'
        WHEN EXTRACT(MONTH FROM PDD_DATA) IN (6,7,8)
            THEN 'INVERNO'
        ELSE 'PRIMAVERA'
    END AS ESTACAO
FROM DW_USER.ALL_QUALIDADES;

BEGIN
   dbms_mview.refresh('MV_QUALIDADE_STAGE', method => 'C', atomic_refresh => FALSE);
END;
