CREATE OR REPLACE VIEW DW_USER.ALL_QUALIDADES AS

SELECT
    p.PDT_ID,
    p.PDT_NOME,
    p.PDT_PRECO,
    pp.PPD_PDD_ID,
    pp.PPD_PDT_ID,
    pp.PPD_QUANTIDADE,
    pd.PDD_ID,
    pd.PDD_DATA,
    pd.PDD_STT_ID,
    pd.PDD_FOC_ID,
    pd.PDD_QAL_ID,
    q.QAL_NOME,
    pd.PDD_VALOR_TOTAL,
    pd.PDD_VALOR_PAGO
FROM DEV.PRODUTOS p
JOIN DEV.PEDIDOS_PRODUTOS pp ON p.PDT_ID = pp.PPD_PDT_ID
JOIN DEV.PEDIDOS pd ON pp.PPD_PDD_ID = pd.PDD_ID
LEFT JOIN DEV.QUALIDADES q ON pd.PDD_QAL_ID = q.QAL_ID

UNION ALL

SELECT
    hp.HPDT_ID,
    hp.HPDT_NOME,
    hp.HPDT_PRECO,
    hpp.HPPD_PDD_ID,
    hpp.HPPD_PDT_ID,
    hpp.HPPD_QUANTIDADE,
    hpd.HPDD_ID,
    hpd.HPDD_DATA,
    hpd.HPDD_STT_ID,
    hpd.HPDD_FOC_ID,
    hpd.HPDD_QAL_ID,
    q.QAL_NOME,
    hpd.HPDD_VALOR_TOTAL,
    hpd.HPDD_VALOR_PAGO
FROM DEV.HPRODUTOS hp
JOIN DEV.HPEDIDOS_PRODUTOS hpp ON hp.HPDT_ID = hpp.HPPD_PDT_ID
JOIN DEV.HPEDIDOS hpd ON hpp.HPPD_PDD_ID = hpd.HPDD_ID
LEFT JOIN DEV.QUALIDADES q ON hpd.HPDD_QAL_ID = q.QAL_ID;