-- Comparação da quantidade de produtos pedidos nos meses de cada ano

WITH all_pedidos as (
    SELECT 
        p.PDD_DATA,
        ppd.PPD_QUANTIDADE
    FROM PEDIDOS_PRODUTOS ppd
    JOIN PEDIDOS p ON ppd.PPD_PDD_ID = p.PDD_ID

    UNION ALL

    SELECT
        hp.HPDD_DATA AS PDD_DATA,
        hppd.HPPD_QUANTIDADE AS PPD_QUANTIDADE
    FROM HPEDIDOS_PRODUTOS hppd
    JOIN HPEDIDOS hp ON hppd.HPPD_PDD_ID = hp.HPDD_ID
)

SELECT 
    TO_CHAR(TO_DATE(EXTRACT(MONTH FROM ap.PDD_DATA), 'MM'), 'MONTH') AS MES,
    COALESCE(SUM(CASE WHEN EXTRACT(YEAR FROM ap.PDD_DATA) = 2024 THEN ap.PPD_QUANTIDADE END), 0) AS "2024",
    COALESCE(SUM(CASE WHEN EXTRACT(YEAR FROM ap.PDD_DATA) = 2025 THEN ap.PPD_QUANTIDADE END), 0) AS "2025",
    COALESCE(SUM(CASE WHEN EXTRACT(YEAR FROM ap.PDD_DATA) = 2026 THEN ap.PPD_QUANTIDADE END), 0) AS "2026"
FROM all_pedidos ap
GROUP BY EXTRACT(MONTH FROM ap.PDD_DATA)
ORDER BY EXTRACT(MONTH FROM ap.PDD_DATA)