-- Número de pedidos de cada mes em cada ano

WITH all_pedidos as (
    SELECT 
        p.PDD_ID,
        p.PDD_DATA
    FROM PEDIDOS p

    UNION ALL

    SELECT 
        hp.HPDD_ID AS PDD_ID,
        hp.HPDD_DATA AS PDD_DATA
    FROM HPEDIDOS hp
)

SELECT 
    TO_CHAR(TO_DATE(EXTRACT(MONTH FROM ap.PDD_DATA), 'MM'), 'MONTH') AS MES,
    COALESCE(COUNT(CASE WHEN EXTRACT(YEAR FROM ap.PDD_DATA) = 2024 THEN 1 END), 0) AS "2024",
    COALESCE(COUNT(CASE WHEN EXTRACT(YEAR FROM ap.PDD_DATA) = 2025 THEN 1 END), 0) AS "2025",
    COALESCE(COUNT(CASE WHEN EXTRACT(YEAR FROM ap.PDD_DATA) = 2026 THEN 1 END), 0) AS "2026"
FROM all_pedidos ap
GROUP BY EXTRACT(MONTH FROM ap.PDD_DATA)
ORDER BY EXTRACT(MONTH FROM ap.PDD_DATA)