-- Meses com maior número de pedidos

SELECT
    TO_CHAR(TO_DATE(EXTRACT(MONTH FROM hp.HPDD_DATA), 'MM'), 'MONTH') AS mes,
    COUNT(hp.HPDD_ID) AS Total
FROM HPEDIDOS hp
WHERE EXTRACT(YEAR FROM hp.HPDD_DATA) = '2025'
GROUP BY EXTRACT(MONTH FROM hp.HPDD_DATA)
ORDER BY Total DESC