-- Meses com maior número de pedidos

SELECT
    EXTRACT(MONTH FROM hp.HPDD_DATA) AS mes,
    COUNT(hp.HPDD_ID) AS Total
FROM HPEDIDOS hp
WHERE EXTRACT(YEAR FROM hp.HPDD_DATA) = '2025'
GROUP BY EXTRACT(MONTH FROM hp.HPDD_DATA)
ORDER BY Total DESC