CREATE TABLE "DEV"."DADOS" 
   (	"DATA_DO_PEDIDO" DATE, 
	"STATUS_DO_PEDIDO" VARCHAR2(255 BYTE), 
	"NOME_FORNECEDOR" VARCHAR2(255 BYTE), 
	"PRODUTOS" VARCHAR2(255 BYTE), 
	"QUANTIDADES" VARCHAR2(255 BYTE), 
	"VALOR_TOTAL" NUMBER(5,2), 
	"DIFERENCA" NUMBER(5,2), 
	"VALOR_PAGO" NUMBER(5,2), 
	"QUALIDADE_DO_PRODUTO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;