SELECT
    PDT_NOME,
    SUM(PPD_QUANTIDADE) AS TOTAL_VENDIDO,
    SUM(VALOR_ITEM) AS FATURAMENTO
FROM DW_USER.MV_PEDIDOS_STAGE
GROUP BY PDT_ID, PDT_NOME
ORDER BY FATURAMENTO DESC;

/

SELECT
    PDD_DATA,
    AVG(PDT_PRECO) AS PRECO_MEDIO
FROM DW_USER.MV_PEDIDOS_STAGE
WHERE PDT_ID = 9
GROUP BY PDD_DATA
ORDER BY PDD_DATA;

/

SELECT
    ANO,
    MES,
    SUM(VALOR_ITEM) AS FATURAMENTO
FROM DW_USER.MV_PEDIDOS_STAGE
GROUP BY ANO, MES;

/

SELECT
    ESTACAO,
    PDT_NOME,
    TOTAL_VENDIDO
FROM (
    SELECT
        CASE
            WHEN EXTRACT(MONTH FROM PDD_DATA) IN (12, 1, 2)
                THEN 'VERAO'
            WHEN EXTRACT(MONTH FROM PDD_DATA) IN (3, 4, 5)
                THEN 'OUTONO'
            WHEN EXTRACT(MONTH FROM PDD_DATA) IN (6, 7, 8)
                THEN 'INVERNO'
            ELSE 'PRIMAVERA'
        END AS ESTACAO,
        PDT_NOME,
        SUM(PPD_QUANTIDADE) AS TOTAL_VENDIDO,
        RANK() OVER (
            PARTITION BY
                CASE
                    WHEN EXTRACT(MONTH FROM PDD_DATA) IN (12, 1, 2)
                        THEN 'VERAO'
                    WHEN EXTRACT(MONTH FROM PDD_DATA) IN (3, 4, 5)
                        THEN 'OUTONO'
                    WHEN EXTRACT(MONTH FROM PDD_DATA) IN (6, 7, 8)
                        THEN 'INVERNO'
                    ELSE 'PRIMAVERA'
                END
            ORDER BY SUM(PPD_QUANTIDADE) DESC
        ) AS POSICAO
    FROM DW_USER.MV_PEDIDOS_STAGE
    GROUP BY
        CASE
            WHEN EXTRACT(MONTH FROM PDD_DATA) IN (12, 1, 2)
                THEN 'VERAO'
            WHEN EXTRACT(MONTH FROM PDD_DATA) IN (3, 4, 5)
                THEN 'OUTONO'
            WHEN EXTRACT(MONTH FROM PDD_DATA) IN (6, 7, 8)
                THEN 'INVERNO'
            ELSE 'PRIMAVERA'
        END,
        PDT_NOME
)
WHERE POSICAO = 1;