-- EXEMPLO DE MVIEW
CREATE MATERIALIZED VIEW DW_USER.MV_PRODUTO_STAGE
BUILD IMMEDIATE 
REFRESH FORCE
ON DEMAND
AS

SELECT
    ap.PDT_NOME AS PRODUTO_NOME,
    AVG(ap.PDT_PRECO) AS MÉDIA_PREÇO,
    SUM(ap.PPD_QUANTIDADE) AS TOTAL_VENDIDO,
    ap.FOC_NOME,
    TO_CHAR(SUM(ap.PPD_QUANTIDADE * ap.PDT_PRECO),'FML999G999D00','NLS_NUMERIC_CHARACTERS = '',.''NLS_CURRENCY = ''R$''') AS VALOR_FATURAMENTO,
    EXTRACT(MONTH FROM ap.PDD_DATA) || '/' || EXTRACT(YEAR FROM ap.PDD_DATA) AS MES_ANO,
    CASE
        WHEN EXTRACT(MONTH FROM PDD_DATA) IN (12,1,2)
            THEN 'VERAO'
        WHEN EXTRACT(MONTH FROM PDD_DATA) IN (3,4,5)
            THEN 'OUTONO'
        WHEN EXTRACT(MONTH FROM PDD_DATA) IN (6,7,8)
            THEN 'INVERNO'
        ELSE 'PRIMAVERA'
    END AS ESTACAO
FROM DW_USER.ALL_PRODUTOS ap
GROUP BY 
    ap.PDT_NOME,
    ap.PPD_QUANTIDADE,
    EXTRACT(MONTH FROM ap.PDD_DATA),
    EXTRACT(YEAR FROM ap.PDD_DATA),
    ap.FOC_NOME,
    CASE
        WHEN EXTRACT(MONTH FROM PDD_DATA) IN (12,1,2)
            THEN 'VERAO'
        WHEN EXTRACT(MONTH FROM PDD_DATA) IN (3,4,5)
            THEN 'OUTONO'
        WHEN EXTRACT(MONTH FROM PDD_DATA) IN (6,7,8)
            THEN 'INVERNO'
        ELSE 'PRIMAVERA'
    END
ORDER BY 
    EXTRACT(YEAR FROM ap.PDD_DATA),
    EXTRACT(MONTH FROM ap.PDD_DATA);

-- refresh na view
BEGIN
   dbms_mview.refresh('MV_PRODUTO_STAGE', method => 'C', atomic_refresh => FALSE);
END;
