-- EXEMPLO DE MVIEW
CREATE MATERIALIZED VIEW DW_USER.MV_PRODUTO_STAGE
BUILD IMMEDIATE 
REFRESH FORCE
ON DEMAND
AS

SELECT
    PDT_ID,
    PDT_NOME,
    PDT_PRECO,
    PPD_PDD_ID,
    PPD_PDT_ID,
    PPD_QUANTIDADE,
    PDD_ID,
    PDD_DATA,
    PDD_STT_ID,
    PDD_FOC_ID,
    PDD_QAL_ID,
    PDD_VALOR_TOTAL,
    PDD_VALOR_PAGO,
    (PPD_QUANTIDADE * PDT_PRECO) AS VALOR_ITEM,
    EXTRACT(YEAR FROM PDD_DATA) AS ANO,
    EXTRACT(MONTH FROM PDD_DATA) AS MES
FROM DW_USER.ALL_PRODUTOS;

-- refresh na view
BEGIN
   dbms_mview.refresh('MV_PRODUTO_STAGE', method => 'C', atomic_refresh => FALSE);
END;
/